### ISSUE TITLE
增加制品库功能，实现CI产物的输出及转存等

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci#142]
**您有什么需求，是否与某个功能或问题相关? 请描述**

**你想要的解决方案是什么**

#
* 请你通过留下👍 表情为此issue投票，帮助社区和维护者优先考虑这个请求；
* 请不要留下 "+1 "或 "me too"的评论，它们会给问题订阅者带来额外的噪音，并且无助于优先处理请求。
* 如果你有兴趣在这个问题上工作，或者已经提交了pull request，请留下评论.

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by stainzhu** [comment]
提供一个基础的jdk镜像，基于构建好的项目的jar，来自动构建服务镜像,

**Comment by colynn** [comment]
## Background
当前可以使用`atomci` 构建/部署，但是目前无法满足构建过程中的产生输出物的转存， 比如想下载编译的二进制文件、镜像或是chart等。

## Proposal

- [ ] 1. 新增自定义脚本的stage, 让用户可以自定义实现对构建物的自定义处理

- [ ] 2. 新增支持S3协议类型的artifacts step,  用户定义可以更简化的实现构建物的转存
eg: 
```yaml
        artifacts:
          - name: file
            path: /tmp/file
            s3:
              key: my-file
```

## References

*  https://argoproj.github.io/argo-workflows/key-only-artifacts/
