### ISSUE TITLE
V2.0 使用argo workflow替换Jenkins 的Proposal

### ISSUE THREAD

**Issue by colynn** [go-atomci/atomci#191]
**您有什么需求，是否与某个功能或问题相关? 请描述**

因为atomci 1.0版本的pipeline对于jenkins的依赖过多，且灵活性不够，并且Jenkins与代码主程序是是割裂，也经常性出现安全漏洞；

另外一个好的cicd平台肯定是需要大家一起共建才能完成，故v2.0的版本也会引入插件化的理念，让我们每个人均可以定义/贡献自己的流程，期望argo workflow的替换可以成功，之后主要的进程会更新在这个issue内。

**你想要的解决方案是什么**

如题

#
* 请你通过留下👍 表情为此issue投票，帮助社区和维护者优先考虑这个请求；
* 请不要留下 "+1 "或 "me too"的评论，它们会给问题订阅者带来额外的噪音，并且无助于优先处理请求。
* 如果你有兴趣在这个问题上工作，或者已经提交了pull request，请留下评论.

* Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by colynn** [comment]
- [x] argo-workflow dockerfile结构
- [ ] try to use argo-workflow's openAPI

**Comment by fanhousanbu** [comment]
argo-workflow是计划怎么部署？由atomci在引入构建机的时候自动部署吗？

**Comment by colynn** [comment]
> argo-workflow是计划怎么部署？由atomci在引入构建机的时候自动部署吗？

计划是先走openAPI的方式先将argo-workflow 引入进来，通过多容器的方式来运行；

**Comment by colynn** [comment]
## Try to use argo-workflow open API

### Generate Token
```sh
# create role
kubectl create role atomci -n argo  --verb=list,update,create --resource=workflows.argoproj.io

# create serviceaccount
kubectl create sa atomci -n argo

# create rolebinding
kubectl create rolebinding atomci-binding -n argo --role=atomci --serviceaccount=argo:atomci

### get token
kubectl -n argo describe sa argo-server |grep secrets

# atomci-token-d4zgj get from the above's command
kubectl -n argo get secrets atomci-token-d4zgj -o=jsonpath='{.data.token}' | base64 --decode

```

### Token Usage&Test

```sh
ARGO_TOKEN="Bearer $(kubectl get secret jenkins.service-account-token -o=jsonpath='{.data.token}' | base64 --decode)"
echo $ARGO_TOKEN 

curl https://localhost:2746/api/v1/workflows/argo -H "Authorization: $ARGO_TOKEN"
# 200 OK
```

**Comment by colynn** [comment]
**the mapping of `atomci` core concept and `argo-workflow`**

| AtomCI      |  Argo-workflow |
| ----------- | ----------- |
| 任务模板      |  Container 类型的template   |
| 项目流程      |  Workflow template        |
| 构建部署-创建流水线 |   submit --from workflowtemplate/  with parameters |
| 流水线 |    workflow instance |

**Comment by colynn** [comment]
## artifacts的使用注意

如果我们想通过artifacts的属性来传递构建物，那么首先需要正确[配置Artifact Repository Ref](https://argoproj.github.io/argo-workflows/configure-artifact-repository/).

You can reduce duplication in your templates by configuring repositories that can be accessed by any workflow. This can also remove sensitive information from your templates.

When you want to use any keyword(eg `artifact`) , you should remember this [__link__](https://argoproj.github.io/argo-workflows/fields/#artifact) will give you a lot of help.

**Comment by colynn** [comment]
## argo-workflowTemplate in real world
* clone
* build
* docker-image & publish

### requirements
```sh
# create docker-config secret
kubectl create secret generic docker-config -n argo --from-file=/root/.docker/config.json
```

```yaml
# create  Minio secret
# TODO: accesskey/secretkey you need change to real.
apiVersion: v1
data:
  accesskey: x
  secretkey: x
kind: Secret
metadata:
  name: s3-credentials
  namespace: argo
type: Opaque
```

### workflow template
```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-sample
  annotations:
    workflows.argoproj.io/description: |
      This workflows builds and tests Argo Workflows.
      
      It demonstrates:
      * Clone/ Build
spec:
  serviceAccountName: argo
  arguments:
    parameters:
      - name: branch
        value: master
  entrypoint: main

  volumes:
    - hostPath:
        path: /tmp/codespace/
        type: Directory
      name: work
    - hostPath:
        path: /var/run/docker.sock
        type: Socket
      name: dockersock
    # Mount the configuration so we can push the image.
    # This should create the /.docker/config.json file.
    - name: docker-config
      secret:
        secretName: docker-config

  templates:
    - name: main
      steps:
      - - name: clone
          template: clone
      - - name: build
          template: build
      - - name: docker-image
          template: image

    - name: clone
      container:
        image: golang:1.18
        workingDir: /go/codespace/src
        command: [ sh, -euxc ]
        args:
          - |
            rm -rf golang-app-demo;  git clone -v -b "{{workflow.parameters.branch}}"  --single-branch https://github.com/go-atomci/golang-app-demo.git 
        volumeMounts:
          - mountPath: /go/codespace/src
            name: work
            subPath: src
    - name: build
      container:
        image: golang:1.18
        workingDir: /go/codespace/src
        command: [ sh, -euxc ] 
        args:
          - |
            cd golang-app-demo; go build -o bin/sample  cmd/sample/main.go 
        volumeMounts:
          - mountPath: /go/codespace/src
            name: work
            subPath: src 
      outputs:
        artifacts:
          - name: sample-binary
            path: golang-app-demo/bin/sample
            s3:
              endpoint: minio-default.component:9000
              bucket: argo-artifacts
              insecure: true
              key: sample.tgz
              accessKeySecret:
                name: s3-credentials
                key: accesskey
              secretKeySecret:
                name: s3-credentials
                key: secretkey

    - name: image
      container:
        image: alpine:3.13
        workingDir: /go/codespace/src
        command: [ sh, -euxc ]
        args:
          - |
            [ -f docker-19.03.15.tgz ] ||  wget http://pkg.infra.sensetime.com/artifactory/depend/gitlab/docker-19.03.15.tgz ;
            tar --extract --file docker-19.03.15.tgz --strip-components 1 --directory /usr/local/bin/ ;
            docker version ;
            cd golang-app-demo ; 
            docker build -t 10.151.3.75/library/golang-app-demo:latest  -f Dockerfile . ;
            docker push 10.151.3.75/library/golang-app-demo:latest
        volumeMounts:
          - mountPath: /go/codespace/src
            name: work
            subPath: src
          - mountPath: /var/run/docker.sock
            name: dockersock
          - name: docker-config
            mountPath: /.docker
        env:
          - name: DOCKER_CONFIG
            value: /.docker
```

### then run it
